/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myFirstWebApp;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static double dailyCalorieDeficit(ArrayList<Double> nutritiveValuesList,String gender,double height,double weight,Integer age){
        double basalMethobolismSpeed=0;
        if(gender.equals("male")) {
            basalMethobolismSpeed=66+(9.6*weight)+(1.7*height)-4.7*age;
        }
        else if(gender.equals("female")) {
            basalMethobolismSpeed=665+(9.6*weight)+(1.7*height)-4.7*age;
        }
        else {
            throw new ArithmeticException("Invalid gender");
        }

        return nutritiveValuesList.stream().reduce(0.0, (a,b) ->a+b) - basalMethobolismSpeed;

    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        ArrayList<Double> nutritiveValuesList = new ArrayList<>();
        nutritiveValuesList.add(50.0);
        nutritiveValuesList.add(50.0);
        nutritiveValuesList.add(50.0);
        nutritiveValuesList.add(50.0);
        nutritiveValuesList.add(50.0);
        
        System.out.println(dailyCalorieDeficit(nutritiveValuesList, "female", 180, 90, 20)); 
    }
}
